# Generated by Django 5.1.7 on 2025-04-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='email_etudiant',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='article',
            name='filiere',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='article',
            name='niveau',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='article',
            name='nom_etudiant',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='article',
            name='numero_etudiant',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='article',
            name='photo_etudiant',
            field=models.ImageField(blank=True, null=True, upload_to='etudiants/'),
        ),
        migrations.AddField(
            model_name='article',
            name='prenom_etudiant',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='article',
            name='telephone',
            field=models.CharField(default='', max_length=20),
        ),
    ]
